/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "../components/Card/Card";
import Layout from "../components/Layout/Layout";
import Pagination from "../components/Pagination/Pagination";
import { getTvShow } from "../services";

export default function Home() {
  const [allTvShow, setAllTvShow] = useState([]);

  useEffect(() => {
    getTvShow().then((res) => setAllTvShow(res.data));
  }, []);

  const [currentPage, setCurrentPage] = useState(1);
  const listPerPage = 28;
  const indexOfLastList = currentPage * listPerPage;
  const indexOfFirstList = indexOfLastList - listPerPage;
  const currentList = allTvShow.slice(indexOfFirstList, indexOfLastList);

  const pageNumbers = Math.ceil(allTvShow.length / listPerPage);

  const nextPage = () => {
    if (currentPage < pageNumbers) {
      let nextPage = currentPage + 1;
      setCurrentPage(nextPage);
    }
  };

  const prevPage = () => {
    if (currentPage > 1) {
      let prevPage = currentPage - 1;
      setCurrentPage(prevPage);
    }
  };

  return (
    <Layout>
      <Head>
        <title>Vozy-TV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="display-4 text-muted">Show available for you.. </h1>
      <div className="container">
        <div className="row">
          {allTvShow.length > 0 &&
            currentList.map((tv, index) => (
              <Card key={index} src={tv.image.medium} title={tv.name} />
            ))}
        </div>
      </div>
      <Pagination
        currentPage={currentPage}
        pageNumbers={pageNumbers}
        nextPage={nextPage}
        prevPage={prevPage}
      />
    </Layout>
  );
}
