/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

import Layout from "../components/Layout/Layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Vozy-TV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>HOLA</h1>
    </Layout>
  );
}
